import { useMemo, useState } from 'react'
import { BedDouble, ChevronDown, MapPin, Search, SlidersHorizontal, Star } from 'lucide-react'
import { hotels } from '../data/travel'
import { HotelCard } from '../components/Cards'
import PageHero from '../components/PageHero'
import { EmptyState } from '../components/PageChrome'

export default function HotelsPage() {
  const [query, setQuery] = useState('')
  const [type, setType] = useState('All stays')
  const [max, setMax] = useState(900)
  const filtered = useMemo(() => hotels.filter((item) => (type === 'All stays' || item.type === type) && item.price <= max && `${item.name} ${item.location}`.toLowerCase().includes(query.toLowerCase())), [query, type, max])
  return <main id="main-content"><PageHero compact eyebrow="Hotels" title={<>Stay somewhere<br />worth remembering.</>} text="Characterful hotels, restorative resorts, and thoughtful spaces—chosen for the way they make a trip feel." image="https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2200&q=90"><div className="page-inline-search glass-panel"><label><span>Destination</span><div><MapPin size={15} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="City or hotel" /></div></label><label><span>Check in</span><input type="date" /></label><label><span>Check out</span><input type="date" /></label><label><span>Guests</span><select><option>2 guests · 1 room</option><option>1 guest · 1 room</option><option>4 guests · 2 rooms</option></select></label><button className="btn btn--aqua"><Search size={17} />Search stays</button></div></PageHero><section className="catalog-section container"><div className="catalog-toolbar"><div className="catalog-search"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search hotels" aria-label="Search hotels" /></div><label><span>Property</span><select value={type} onChange={(e) => setType(e.target.value)}>{['All stays', 'Luxury', 'Boutique', 'Resort', 'Villa'].map((item) => <option key={item}>{item}</option>)}</select><ChevronDown size={14} /></label><label><span>Nightly budget</span><select value={max} onChange={(e) => setMax(+e.target.value)}><option value="900">Up to $900</option><option value="600">Up to $600</option><option value="400">Up to $400</option></select><ChevronDown size={14} /></label><button className="btn btn--outline"><SlidersHorizontal size={15} />All filters</button><p>{filtered.length} beautiful stays</p></div><div className="hotel-catalog-layout"><aside className="filter-panel hotel-filters"><div className="filter-head"><strong>Refine your stay</strong><button onClick={() => { setType('All stays'); setMax(900) }}>Reset</button></div>{['Pool', 'Breakfast', 'Free cancellation', 'Gym', 'Parking', 'Wi-Fi'].map((item) => <label className="switch-row" key={item}><span>{item}</span><input type="checkbox" /><i /></label>)}<label className="price-range"><span>Guest rating <strong>4.0+</strong></span><input type="range" min="3" max="5" step="0.1" defaultValue="4" /></label><div className="stay-promise"><Star fill="currentColor" /><p><strong>The TIME TO FLY stay promise</strong><br />Every stay is quality checked and support is always included.</p></div></aside><div className="hotel-catalog">{filtered.length ? filtered.map((hotel) => <HotelCard hotel={hotel} key={hotel.id} />) : <EmptyState title="No stays found" text="Try another destination or budget." />}</div></div></section></main>
}
