import { useState } from 'react'
import { ArrowRight, Check, Plane, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { packages } from '../data/travel'
import { useTravel } from '../context/TravelContext'
import PageHero from '../components/PageHero'
import { Stars } from '../components/Motion'

export default function PackagesPage() {
  const { addBooking, notify } = useTravel()
  const [active, setActive] = useState(packages[0])
  const book = () => { addBooking({ type: 'Package', title: active.name, date: 'Oct 12, 2026', status: 'Confirmed', total: active.price }); notify(`${active.name} added to your trip`) }
  return <main id="main-content"><PageHero eyebrow="Travel packages" title={<>Everything,<br /><em>beautifully handled.</em></>} text="One thoughtful booking for flights, a beautiful stay, local experiences, and every transfer in between." image="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=90" /><section className="package-detail container"><div className="package-choice-list">{packages.map((item) => <button className={active.id === item.id ? 'is-active' : ''} onClick={() => setActive(item)} key={item.id}><img src={item.image} alt="" /><span><small>{item.duration}</small><strong>{item.name}</strong><em>From ${item.price.toLocaleString()}</em></span><ArrowRight size={17} /></button>)}</div><div className="package-main"><img className="package-main__image" src={active.image} alt={active.name} /><div className="package-main__body"><span className="pill pill--mint">{active.discount}% off</span><span className="micro-label">{active.location} · Curated journey</span><h2>{active.name}</h2><Stars rating={active.rating} count={428} /><p>A beautifully paced escape with the essentials handled and enough freedom to make it your own.</p><div className="package-includes"><strong>Your journey includes</strong>{active.includes.map((item) => <span key={item}><Check size={15} />{item}</span>)}</div><div className="package-itinerary">{['Arrive & settle in', 'A day at your own pace', 'The signature experience', 'One last delicious morning', 'Depart with memories'].map((item, index) => <div key={item}><i>{index + 1}</i><span><strong>{item}</strong><small>Day {index + 1} · Included experience and transfers</small></span></div>)}</div></div></div><aside className="booking-summary"><div className="booking-summary__price"><span>Package from</span><strong>${active.price.toLocaleString()}</strong><small>per person, based on 2 travelers</small></div><div className="price-breakdown"><p><span>Travel package</span><b>${active.original.toLocaleString()}</b></p><p><span>TIME TO FLY saving</span><b className="discount">−${(active.original - active.price).toLocaleString()}</b></p><p><span>Taxes and fees</span><b>Included</b></p></div><button className="btn btn--aqua" onClick={book}>Choose this package <ArrowRight size={16} /></button><small><ShieldCheck size={14} />Free cancellation within 48 hours</small><div><Plane size={17} /><p><strong>Need a different pace?</strong><br />Our trip team can tailor dates, rooms, and experiences.</p></div></aside></section><section className="assurance-banner"><div className="container"><div><span><ShieldCheck /></span><p><strong>Every package is travel-ready.</strong><strong> 24/7 support, secure payments, and clear terms included.</strong></p></div><Link to="/support">Talk to a travel specialist <ArrowRight size={15} /></Link></div></section></main>
}
