import { ArrowRight, Check, CreditCard, LockKeyhole, ShieldCheck, Ticket, Wallet } from 'lucide-react'
import { useState } from 'react'
import { useTravel } from '../context/TravelContext'

const methods = ['Credit card', 'Debit card', 'Digital wallet', 'Bank transfer']
const coupons = [['FLY10', '10% off flights', 'Minimum $600 · Expires Dec 31, 2026'], ['TRAVEL20', '$200 off packages', 'Minimum $1,500 · Expires Nov 30, 2026'], ['WELCOME15', '15% off your first stay', 'Minimum $400 · Expires Oct 31, 2026']]

export function PaymentPage() {
  const { notify } = useTravel()
  const [method, setMethod] = useState('Credit card')
  const [coupon, setCoupon] = useState('')
  const [discount, setDiscount] = useState(0)
  const apply = () => { const found = coupons.find(([code]) => code === coupon.toUpperCase()); if (!found) return notify('That coupon could not be found', 'error'); setDiscount(found[0] === 'FLY10' ? 96 : found[0] === 'TRAVEL20' ? 200 : 78); notify(`${coupon.toUpperCase()} applied`) }
  return <main id="main-content" className="checkout-page"><div className="container"><div className="checkout-head"><span className="eyebrow"><i />Secure checkout</span><h1>Complete your booking.</h1><p><LockKeyhole />Encrypted and protected from start to finish</p></div><div className="checkout-layout"><form className="checkout-form"><section><span>1</span><div><h2>Traveler information</h2><p>Enter names exactly as they appear on the passport.</p><div className="form-row"><label>First name<input defaultValue="Alex" /></label><label>Last name<input defaultValue="Morgan" /></label></div><div className="form-row"><label>Email<input type="email" defaultValue="alex.morgan@example.com" /></label><label>Phone<input type="tel" defaultValue="+1 212 555 0192" /></label></div></div></section><section><span>2</span><div><h2>Payment method</h2><p>Choose how you’d like to pay.</p><div className="payment-methods">{methods.map((item, index) => <button className={method === item ? 'is-active' : ''} onClick={() => setMethod(item)} type="button" key={item}>{[CreditCard, Wallet, Ticket][index < 3 ? index : 0]}<span>{item}</span>{method === item && <Check />}</button>)}</div><div className="form-row"><label>Name on card<input defaultValue="Alex Morgan" /></label><label>Card number<input defaultValue="4242 4242 4242 4242" /></label></div><div className="form-row"><label>Expiry<input defaultValue="10 / 29" /></label><label>Security code<input defaultValue="123" /></label></div></div></section><label className="check-label"><input type="checkbox" />Save payment details for a faster checkout next time</label></form><aside className="checkout-summary"><div className="checkout-summary__head"><h2>Your booking</h2><span>Confirmed</span></div><div className="checkout-flight"><span>TF</span><div><strong>JFK <ArrowRight /> DPS</strong><p>Oct 12, 2026 · 18:40</p><small>SkyAtlantic · Economy · 2 adults</small></div></div><div className="price-breakdown"><p><span>Flights × 2</span><b>$1,484</b></p><p><span>Taxes and airline fees</span><b>$214</b></p><p><span>Service fee</span><b>$38</b></p>{discount > 0 && <p className="discount"><span>Coupon {coupon.toUpperCase()}</span><b>−${discount}</b></p>}<hr /><p><span>Total</span><b>${1736 - discount} USD</b></p></div><div className="coupon-field"><input value={coupon} onChange={(e) => setCoupon(e.target.value)} placeholder="Promo code" /><button type="button" onClick={apply}>Apply</button></div><button className="btn btn--aqua" onClick={() => notify('Payment authorized securely')}>Pay ${(1736 - discount).toLocaleString()} <LockKeyhole /></button><p className="secure-payment"><ShieldCheck />Your payment is encrypted and protected. No card details are stored on this device.</p><div className="insurance-offer"><span><ShieldCheck /></span><div><strong>Travel with peace of mind</strong><p>Add flexible cancellation and medical coverage from $24.</p></div><button type="button">Add</button></div></aside></div></div></main>
}
