import { useState } from 'react'
import { CalendarDays, Check, ChevronLeft, ChevronRight, GripVertical, Plus, Trash2, X } from 'lucide-react'
import { useTravel } from '../context/TravelContext'
import TripSidebar from '../components/TripSidebar'
import TripCalendar from '../components/TripCalendar'
import TripMap from '../components/TripMap'

const initialDays = [
  { date: '12 Oct', title: 'Arrival & slow evening', weather: '28°', items: [{ time: '14:20', type: 'Flight', title: 'Land in Denpasar', detail: 'SkyAtlantic TF 218 · Terminal 2' }, { time: '17:00', type: 'Hotel', title: 'Check in at Solei Resort', detail: 'Ubud · 6 nights' }, { time: '19:30', type: 'Food', title: 'Dinner at Locavore', detail: 'Table for 2 · reservation saved' }] },
  { date: '13 Oct', title: 'Ubud, slowly', weather: '29°', items: [{ time: '08:00', type: 'Activity', title: 'Ubud art market walk', detail: 'Meet your local guide at the east gate' }, { time: '14:00', type: 'Hotel', title: 'Pool time & downtime', detail: 'No alarms needed' }] },
  { date: '14 Oct', title: 'Into the island', weather: '30°', items: [{ time: '07:30', type: 'Activity', title: 'Nusa Penida island day', detail: 'Private boat · snorkeling gear included' }] },
]
const typeIcon = { Flight: '✈', Hotel: '⌂', Food: '♨', Activity: '✦' }

export default function TripsPage() {
  const { notify } = useTravel()
  const [view, setView] = useState('Timeline')
  const [days, setDays] = useState(initialDays)
  const [adding, setAdding] = useState(false)
  const [activity, setActivity] = useState({ title: '', time: '12:00', type: 'Activity' })
  const addActivity = (event) => { event.preventDefault(); if (!activity.title) return; setDays((items) => items.map((day, index) => index === 0 ? { ...day, items: [...day.items, { ...activity }] } : day)); setAdding(false); setActivity({ title: '', time: '12:00', type: 'Activity' }); notify('Activity added to Day 1') }
  const move = (item, direction) => setDays((all) => all.map((day) => { const index = day.items.findIndex((x) => x.title === item.title); const target = index + direction; if (index < 0 || target < 0 || target >= day.items.length) return day; const next = [...day.items]; [next[index], next[target]] = [next[target], next[index]]; return { ...day, items: next } }))
  const remove = (item) => { setDays((all) => all.map((day) => ({ ...day, items: day.items.filter((x) => x.title !== item.title) }))); notify('Activity removed') }
  const addSailing = () => { setDays((all) => all.map((day, index) => index === 2 ? { ...day, items: [...day.items, { time: '17:00', type: 'Activity', title: 'Sunset sailing', detail: 'Private catamaran · Uluwatu' }] } : day)); notify('Sunset sailing added to Day 3') }
  return <main id="main-content" className="planner-page"><header className="planner-header"><div><span className="micro-label">My trips / Bali</span><h1>My Bali Trip</h1><p><CalendarDays />Oct 12–19, 2026 · 7 days · 2 travelers</p></div><div><span className="pill pill--mint">Planning</span><button className="btn btn--outline" onClick={() => notify('Invite link copied to clipboard')}>Share trip</button><button className="btn btn--dark" onClick={() => setAdding(true)}><Plus />Add to trip</button></div></header><div className="planner-viewbar"><div>{['Timeline', 'Calendar', 'Map'].map((item) => <button className={view === item ? 'is-active' : ''} onClick={() => setView(item)} key={item}>{item}</button>)}</div><span>Last saved just now</span></div>{view === 'Timeline' && <div className="planner-layout"><section className="itinerary-list">{days.map((day, dayIndex) => <article className="itinerary-day" key={day.date}><header><div><span>Day {dayIndex + 1}</span><strong>{day.title}</strong></div><div><b>{day.date}</b><span>{day.weather} · Bali</span></div></header><div>{day.items.map((item) => <div className="itinerary-item" key={item.title}><GripVertical size={16} /><time>{item.time}</time><span className="itinerary-icon">{typeIcon[item.type]}</span><div><small>{item.type}</small><strong>{item.title}</strong><p>{item.detail}</p></div><div><button onClick={() => move(item, -1)} aria-label="Move activity earlier"><ChevronLeft /></button><button onClick={() => move(item, 1)} aria-label="Move activity later"><ChevronRight /></button><button onClick={() => remove(item)} aria-label="Remove activity"><Trash2 /></button></div></div>)}<button className="add-activity-inline" onClick={() => setAdding(true)}><Plus />Add activity</button></div></article>)}</section><TripSidebar days={days} addSailing={addSailing} /></div>}{view === 'Calendar' && <TripCalendar days={days} />}{view === 'Map' && <TripMap />}{adding && <div className="modal-backdrop"><form className="activity-modal" onSubmit={addActivity}><button type="button" className="icon-button" onClick={() => setAdding(false)}><X /></button><span className="eyebrow"><i />Add to Day 1</span><h2>What should happen here?</h2><label>Activity<input autoFocus value={activity.title} onChange={(e) => setActivity({ ...activity, title: e.target.value })} placeholder="e.g. Sunset at Tanah Lot" /></label><div><label>Time<input type="time" value={activity.time} onChange={(e) => setActivity({ ...activity, time: e.target.value })} /></label><label>Type<select value={activity.type} onChange={(e) => setActivity({ ...activity, type: e.target.value })}><option>Activity</option><option>Food</option><option>Hotel</option><option>Flight</option></select></label></div><button className="btn btn--dark" type="submit">Add to itinerary</button></form></div>}</main>
}
