import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Area, AreaChart } from 'recharts'
import { MoreHorizontal, TrendingUp } from 'lucide-react'
import { bookingData, revenueData, userGrowth } from '../data/analytics'

export default function AdminCharts() {
  return <div className="admin-chart-grid"><section className="admin-card revenue-chart"><ChartHead eyebrow="Performance" title="Revenue overview" select /><div className="chart-total"><strong>$6.24M</strong><span><TrendingUp />16.8%</span></div><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenueData}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2d8880" stopOpacity=".4" /><stop offset="1" stopColor="#2d8880" stopOpacity="0" /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Area type="monotone" dataKey="revenue" stroke="#277d76" strokeWidth={2.5} fill="url(#revenue)" /></AreaChart></ResponsiveContainer></section><section className="admin-card flight-mix"><ChartHead eyebrow="Inventory" title="Flight booking mix" button /><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{ name: 'Economy', value: 68 }, { name: 'Premium', value: 21 }, { name: 'Business', value: 8 }, { name: 'First', value: 3 }]} innerRadius={65} outerRadius={88} paddingAngle={4}>{['#277d76', '#e0a45c', '#536d8a', '#b6d4ce'].map((color) => <Cell fill={color} key={color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div><strong>12,842</strong><span>Total flights</span></div></div><div className="chart-legend">{[['Economy', '68%'], ['Premium', '21%'], ['Business', '8%'], ['First class', '3%']].map(([name, value]) => <p key={name}><i />{name}<b>{value}</b></p>)}</div></section><section className="admin-card booking-chart"><ChartHead eyebrow="Booking trends" title="Flights & hotels" total="+12.4%" /><ResponsiveContainer width="100%" height="100%"><BarChart data={bookingData} barGap={4}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis /><Tooltip /><Legend /><Bar dataKey="flights" fill="#277d76" radius={[5, 5, 0, 0]} /><Bar dataKey="hotels" fill="#e0a45c" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></section><section className="admin-card growth-chart"><ChartHead eyebrow="Community" title="User growth" button /><ResponsiveContainer width="100%" height="100%"><LineChart data={userGrowth}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line type="monotone" dataKey="users" stroke="#6b4ea0" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></section></div>
}

function ChartHead({ eyebrow, title, select, total, button }) { return <div className="card-head"><div><span className="micro-label">{eyebrow}</span><h2>{title}</h2></div>{select && <select><option>Last 9 months</option><option>This year</option></select>}{total && <span className="chart-total-inline">{total}</span>}{button && <button aria-label="Chart options"><MoreHorizontal /></button>}</div> }
