import { Bar, BarChart, CartesianGrid, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Area, AreaChart } from 'recharts'
import { useState } from 'react'
import { TrendingUp } from 'lucide-react'
import { bookingData, revenueData, userGrowth } from '../data/analytics'

export default function AdminCharts() {
  const [range, setRange] = useState('9 months')
  const [mix, setMix] = useState('Economy')
  const [booking, setBooking] = useState('Flights')
  const revenue = range === '30 days' ? revenueData.slice(-2) : range === '3 months' ? revenueData.slice(-3) : range === '6 months' ? revenueData.slice(-6) : range === '7 days' ? revenueData.slice(-1) : revenueData
  const chartData = bookingData.map((item) => ({ ...item, selected: booking === 'Flights' ? item.flights : booking === 'Hotels' ? item.hotels : booking === 'Packages' ? Math.round(item.flights * .65) : Math.round(item.hotels * .7) }))
  return <div className="admin-chart-grid"><section className="admin-card revenue-chart"><ChartHead eyebrow="Performance" title="Revenue overview" value={range} onChange={setRange} options={['7 days', '30 days', '3 months', '6 months', '1 year', '9 months']} /><div className="chart-total"><strong>$6.24M</strong><span><TrendingUp />16.8%</span></div><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2d8880" stopOpacity=".4" /><stop offset="1" stopColor="#2d8880" stopOpacity="0" /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Area type="monotone" dataKey="revenue" stroke="#277d76" strokeWidth={2.5} fill="url(#revenue)" /></AreaChart></ResponsiveContainer></section><section className="admin-card flight-mix"><ChartHead eyebrow="Inventory" title="Flight booking mix" value={mix} onChange={setMix} options={['Economy', 'Premium', 'Business', 'First class']} /><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{ name: mix, value: 68 }, { name: 'Other cabins', value: 32 }]} innerRadius={65} outerRadius={88} paddingAngle={4} dataKey="value" nameKey="name"><Pie data={[{ name: mix, value: 68 }, { name: 'Other cabins', value: 32 }]} dataKey="value" fill="#277d76" /><Pie data={[{ name: mix, value: 68 }, { name: 'Other cabins', value: 32 }]} dataKey="value" fill="#e0a45c" /></Pie><Tooltip /></PieChart></ResponsiveContainer><div><strong>68%</strong><span>{mix} share</span></div></div><div className="chart-legend"><p><i />{mix}<b>68%</b></p><p><i />Other cabins<b>32%</b></p></div></section><section className="admin-card booking-chart"><ChartHead eyebrow="Booking trends" title={`${booking} bookings`} value={booking} onChange={setBooking} options={['Flights', 'Hotels', 'Packages', 'Experiences']} total="+12.4%" /><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="selected" fill="#277d76" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></section><section className="admin-card growth-chart"><ChartHead eyebrow="Community" title="User growth" total="+32.2%" /><ResponsiveContainer width="100%" height="100%"><LineChart data={userGrowth}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line type="monotone" dataKey="users" stroke="#536d8a" strokeWidth={2.5} /></LineChart></ResponsiveContainer></section></div>
}

function ChartHead({ eyebrow, title, value, onChange, options, total }) { return <div className="card-head"><div><span className="micro-label">{eyebrow}</span><h2>{title}</h2></div>{options && <select value={value} onChange={(event) => onChange(event.target.value)} aria-label={`${title} filter`}>{options.map((option) => <option key={option}>{option}</option>)}</select>}{total && <span className="chart-total-inline">{total}</span>}</div> }
