import { ArrowUpRight, Clock3, MoreHorizontal } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAdmin } from '../context/AdminContext'
import { flights as liveFlights } from '../data/travel'

export default function AdminTables() {
  const { state } = useAdmin()
  const rows = state.bookings.slice(0, 6)
  return <><section className="admin-card recent-admin-bookings"><div className="card-head"><div><span className="micro-label">Live operations</span><h2>Recent bookings</h2></div><Link className="btn btn--outline" to="/admin/bookings">View all bookings <ArrowUpRight /></Link></div><div className="admin-table"><div className="admin-table__head"><span>Booking</span><span>Customer</span><span>Type</span><span>Amount</span><span>Status</span><span>Date</span><span /></div>{rows.map((item) => <div className="admin-table__row" key={item.id}><strong>{item.id}</strong><span>{item.customer}</span><span>{item.type}</span><b>${item.amount.toLocaleString()}</b><span className={`status-chip status-${item.status.toLowerCase()}`}>{item.status}</span><span>{item.date}</span><Link to="/admin/bookings" aria-label={`View booking ${item.id}`}><MoreHorizontal /></Link></div>)}</div></section><section className="admin-card flight-operations"><div className="card-head"><div><span className="micro-label">Live inventory</span><h2>Flight schedule</h2></div><Link className="btn btn--outline" to="/admin/flights">Manage schedules</Link></div>{state.flights.map((flight) => <div key={flight.id}><span className="airline-code" style={{ '--accent': liveFlights.find((item) => item.from === flight.departure && item.to === flight.arrival)?.accent || '#277d76' }}>{flight.flightNumber.replace(/\s/g, '').slice(0, 2)}</span><p><strong>{flight.flightNumber} · {flight.departure} → {flight.arrival}</strong><small>{flight.airline} · {flight.aircraft}</small></p><span><Clock3 />{flight.departTime}</span><span>Gate {flight.gate}</span><i className="status-dot" />{flight.status}<Link to="/admin/flights" aria-label={`Manage ${flight.flightNumber}`}><MoreHorizontal /></Link></div>)}</section></>
}
