import { ArrowRight, HeartHandshake, ShieldCheck, Sparkles } from 'lucide-react'
import { blogPosts, experiences } from '../data/catalog'
import PageHero from './PageChrome'

export function BlogPage() {
  return <main id="main-content"><PageHero eyebrow="The journal" title={<>Stories for people<br />who travel curious.</>} text="Beautiful places, honest advice, and the small details that turn a trip into a story worth keeping." image="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=2200&q=90" /><section className="section container"><div className="blog-categories">{['All stories', 'Travel tips', 'Destinations', 'Budget travel', 'Luxury travel', 'Adventure', 'Food', 'Culture', 'Air travel'].map((item, i) => <button className={i === 0 ? 'is-active' : ''} key={item}>{item}</button>)}</div><div className="blog-feature"><img src={blogPosts[0].image} alt={blogPosts[0].title} /><div><span>Featured · {blogPosts[0].category}</span><h2>{blogPosts[0].title}</h2><p>Some of the best places reveal themselves slowly. A local morning, a road less traveled, and a better way to fall into a place.</p><small>By {blogPosts[0].author} · Sep 18, 2026 · {blogPosts[0].read} read</small><button className="btn btn--dark">Read the story <ArrowRight /></button></div></div><div className="blog-grid">{[...blogPosts, ...experiences.slice(0, 3).map((x) => ({ ...x, category: x.category, title: x.title, author: 'TIME TO FLY Editors', date: 'Aug 28, 2026', read: '5 min' }))].map((post) => <article key={post.id}><img src={post.image} alt={post.title} /><div><span>{post.category}</span><h3>{post.title}</h3><p>By {post.author} · {post.read} read</p><button>Read more <ArrowRight /></button></div></article>)}</div></section></main>
}

export function AboutPage() {
  return <main id="main-content"><PageHero eyebrow="About TIME TO FLY" title={<>Travel should feel<br /><em>effortless again.</em></>} text="We bring flights, stays, experiences, and every little in-between detail into one considered journey platform." image="https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=2200&q=90" /><section className="section container about-story"><div><span className="eyebrow"><i />Why we’re here</span><h2>We believe the best journeys feel personal, not complicated.</h2></div><div><p>TIME TO FLY was created around a simple idea: planning a trip can be exciting without also being a second job. We combine smart technology with people who know how to make a journey feel effortless.</p><p>From one flight to an entire month abroad, every detail lives in the same calm, connected place.</p></div></section><section className="values-section"><div className="container"><div className="section-heading section-heading--light"><div><span className="eyebrow"><i />How we travel</span><h2>High standards.<br />Human touch.</h2></div></div><div>{[[HeartHandshake, 'People first', 'Real support from real people, whenever plans change.'], [Sparkles, 'Beautifully useful', 'Technology that feels calm, clear, and genuinely helpful.'], [ShieldCheck, 'Trust, earned', 'Verified partners, secure payments, and honest choices.']].map(([Icon, title, text]) => <article key={title}><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section></main>
}
