import { CalendarDays, ChevronRight, CircleDollarSign, Heart, Luggage, Plane, Wallet } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTravel } from '../context/TravelContext'
import { destinations } from '../data/travel'

const metrics = [['Upcoming trips', '03', Luggage], ['Flight bookings', '05', Plane], ['Hotel bookings', '02', CalendarDays], ['Saved destinations', '03', Heart], ['Travel points', '2,480', CircleDollarSign], ['Total spent', '$3,840', Wallet]]

export default function DashboardOverview() {
  const { bookings, saved } = useTravel()
  const recent = [...bookings, { id: 'TTF-A1B2C3', type: 'Hotel', title: 'Solei Resort, Ubud', date: 'Oct 12–19', status: 'Confirmed', total: 1560 }].slice(0, 4)
  return <div className="dashboard-content"><div className="dashboard-welcome"><div><span>Tuesday, September 23</span><h1>Good morning, Alex.</h1><p>Your next adventure is 19 days away. Everything is ready.</p></div><Link className="btn btn--dark" to="/trips">Plan a new trip</Link></div><div className="user-dashboard-stats">{metrics.map(([label, value, Icon], index) => <article key={label}><span><Icon /></span><div><small>{label}</small><strong>{index === 3 ? String(saved.length + 2).padStart(2, '0') : value}</strong></div><b>→</b></article>)}</div><div className="dashboard-grid"><section className="upcoming-trip dashboard-card"><CardHead eyebrow="Next up" title="My Bali Trip" to="/trips" label="Open trip" /><div className="upcoming-trip__image"><img src={destinations[3].image} alt="Bali" /><div><span>Oct 12–19</span><strong>7 days in Bali</strong><small>2 travelers · 4 bookings</small></div><i>19 days to go</i></div><div className="upcoming-timeline"><span className="is-done"><i>✓</i><b>14:20</b>Land in Denpasar</span><span><i>2</i><b>17:00</b>Check in at Solei</span><span><i>3</i><b>19:30</b>Dinner at Locavore</span></div></section><FlightStatus /><section className="recent-bookings dashboard-card"><CardHead eyebrow="Across all your journeys" title="Recent bookings" to="/dashboard" label="View all" /><div className="booking-table">{recent.map((item) => <div key={item.id}><span className="booking-type">{item.type === 'Flight' ? <Plane /> : <CalendarDays />}</span><div><strong>{item.title}</strong><small>{item.type} · {item.date || 'Jul 22–29'}</small></div><span className="status-chip">{item.status}</span><strong>${(item.total || 820).toLocaleString()}</strong><Link to={item.type === 'Flight' ? `/ticket/${item.id}` : '/dashboard'}><ChevronRight /></Link></div>)}</div></section><Wishlist /></div></div>
}

function CardHead({ eyebrow, title, to, label }) { return <div className="card-head"><div><span className="micro-label">{eyebrow}</span><h2>{title}</h2></div><Link to={to}>{label} <b>→</b></Link></div> }
function FlightStatus() { return <section className="flight-status-card dashboard-card"><CardHead eyebrow="Live status" title="Your next flight" to="/flights" label="Track flight" /><div className="status-route"><span><b>JFK</b><small>New York</small></span><div><Plane /><i /></div><span><b>DPS</b><small>Bali</small></span></div><div className="status-times"><p><strong>18:40</strong><span>Oct 12 · On time</span></p><p><strong>10:55 <sup>+1</sup></strong><span>Oct 13 · Estimated</span></p></div><div className="status-meta"><span>TF 218</span><span>Terminal 2</span><span>Gate B14</span><span>On time</span></div></section> }
function Wishlist() { return <section className="dashboard-wishlist dashboard-card"><CardHead eyebrow="For later" title="Saved places" to="/destinations" label="Explore more" /><div>{destinations.slice(0, 3).map((item) => <Link to={`/destinations/${item.id}`} key={item.id}><img src={item.image} alt="" /><span><strong>{item.name}</strong><small>{item.country} · from ${item.price}</small></span><Heart fill="currentColor" /></Link>)}</div></section> }
