import { Bell, ChevronLeft, ChevronRight, CreditCard, FileText, Heart, LayoutDashboard, Luggage, MessageSquare, Plane, Settings, ShieldCheck, Ticket, Wallet, X, CalendarDays } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, NavLink, useNavigate } from 'react-router-dom'
import Brand from './Brand'

const nav = [['Dashboard', LayoutDashboard, '/dashboard'], ['My trips', Luggage, '/trips'], ['My flights', Plane, '/flights'], ['My hotels', CalendarDays, '/hotels'], ['My tickets', Ticket, '/dashboard'], ['Bookings', FileText, '/trips'], ['Wishlist', Heart, '/destinations'], ['Travel wallet', Wallet, '/checkout'], ['Payments', CreditCard, '/checkout'], ['Notifications', Bell, '/admin/notifications'], ['Messages', MessageSquare, '/support'], ['Travel documents', ShieldCheck, '/trips'], ['Settings', Settings, '/admin/settings']]

export default function DashboardLayout({ children }) {
  const [collapsed, setCollapsed] = useState(() => localStorage.getItem('ttf-dashboard-collapsed') === 'true')
  const [mobile, setMobile] = useState(false)
  const [notificationsOpen, setNotificationsOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const navigate = useNavigate()
  useEffect(() => localStorage.setItem('ttf-dashboard-collapsed', collapsed), [collapsed])
  return <div className={`dashboard-shell ${collapsed ? 'is-collapsed' : ''} ${mobile ? 'drawer-open' : ''}`}><button className="dashboard-overlay" onClick={() => setMobile(false)} aria-label="Close dashboard menu" /><aside className="dashboard-sidebar"><div className="dashboard-brand"><Brand light compact /><div><strong>TIME TO FLY</strong><small>Traveler portal</small></div><button className="icon-button" onClick={() => setMobile(false)} aria-label="Close dashboard menu"><X /></button></div><nav aria-label="Traveler navigation">{nav.map(([label, Icon, to]) => <NavLink key={label} to={to} className={({ isActive }) => isActive ? 'is-active' : ''} onClick={() => setMobile(false)}><Icon /><span>{label}</span>{label === 'Notifications' && <b>3</b>}</NavLink>)}</nav><div className="dashboard-user"><span>AM</span><div><strong>Alex Morgan</strong><small>Traveler plan</small></div><ChevronRight /></div></aside><div className="dashboard-main"><header className="dashboard-topbar"><button className="dashboard-menu" onClick={() => setMobile(true)} aria-label="Open dashboard menu"><span /><span /><span /></button><button className="dashboard-collapse" onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}><ChevronLeft /></button><div className="dashboard-global-search"><span>Search your trips, bookings, tickets…</span></div><Link to="/admin/dashboard" className="btn btn--outline">Admin view</Link><div className="dashboard-topbar-actions"><button className="icon-button" onClick={() => { setNotificationsOpen((value) => !value); setProfileOpen(false) }} aria-label="Open traveler notifications"><Bell /><i /></button><button className="avatar-link" onClick={() => { setProfileOpen((value) => !value); setNotificationsOpen(false) }} aria-label="Open traveler profile">AM</button></div>{notificationsOpen && <div className="dashboard-popover"><div className="popover-head"><strong>Notifications</strong><button onClick={() => setNotificationsOpen(false)}>Close</button></div><p>Your Bali flight is ready for check-in.</p><p>Hotel confirmation received for Oct 12.</p><Link to="/admin/notifications" onClick={() => setNotificationsOpen(false)}>View notification center</Link></div>}{profileOpen && <div className="dashboard-popover dashboard-profile-menu"><button onClick={() => { setProfileOpen(false); navigate('/admin/profile') }}>Profile</button><button onClick={() => { setProfileOpen(false); navigate('/admin/settings') }}>Account settings</button><button onClick={() => { setProfileOpen(false); navigate('/') }}>Back to website</button><button onClick={() => { setProfileOpen(false); navigate('/login') }}>Logout</button></div>}</header>{children}</div></div>
}
