import { ArrowRight, BookOpen, Bus, Clock3, MapPin, Search, ShieldCheck, Utensils } from 'lucide-react'
import { Link } from 'react-router-dom'
import { blogPosts } from '../data/catalog'
import { destinations } from '../data/travel'
import PageHero from './PageChrome'

export default function GuidePage() {
  const destination = destinations[6]
  return <main id="main-content"><PageHero eyebrow="Travel guide" title={<>Know the place.<br /><em>Then go your own way.</em></>} text="Practical local knowledge, remarkable places, and the details that make a destination feel like yours." image={destination.image}><div className="guide-hero-search"><Search /><input placeholder="Search a guide, city, or travel tip" /><button>Search guides</button></div></PageHero><section className="section container"><div className="section-heading"><div><span className="eyebrow"><i />Start with the essentials</span><h2>Everything for a smoother journey</h2></div></div><div className="guide-essentials">{[['best', Clock3, 'Best time to go', 'Weather, seasons, and smart windows for every kind of trip.'], ['food', Utensils, 'Restaurants worth it', 'From excellent street food to tables worth dressing up for.'], ['move', Bus, 'Getting around', 'Clear, calm guidance on airports, trains, taxis, and transfers.'], ['know', BookOpen, 'Local culture', 'Customs, language, traditions, and details that show respect.']].map(([key, Icon, title, text]) => <article key={key}><span><Icon /></span><h3>{title}</h3><p>{text}</p><button>Open guide <ArrowRight /></button></article>)}</div></section><section className="section guide-destination"><div className="container"><div className="guide-destination__image"><img src={destination.image} alt="Tokyo at night" /><span><MapPin />Tokyo, Japan</span></div><div><span className="eyebrow"><i />Guide of the week</span><h2>Tokyo, beyond<br />the obvious.</h2><p>Neighborhood tables, quiet gardens, tiny listening bars, and a route through the city that changes with every neighborhood.</p><div className="guide-facts"><span><strong>18°</strong>September weather</span><span><strong>6 days</strong>Ideal stay</span><span><strong>¥</strong>Currency</span></div><Link className="btn btn--dark" to={`/destinations/${destination.id}`}>Read the Tokyo guide <ArrowRight /></Link></div></div></section><section className="section container"><div className="section-heading"><div><span className="eyebrow"><i />Current thinking</span><h2>Stories for the road</h2><p>Useful ideas, personal recommendations, and the details behind a good trip.</p></div><Link className="text-link" to="/blog">See all stories <ArrowRight /></Link></div><div className="guide-grid">{blogPosts.map((post) => <article className="guide-card" key={post.id}><img src={post.image} alt={post.title} /><div><span>{post.category}</span><h3>{post.title}</h3><p>By {post.author} · {post.read} read</p><Link to="/blog">Read story <ArrowRight /></Link></div></article>)}</div></section><section className="emergency-strip"><div className="container"><ShieldCheck /><div><strong>Useful when you need it most</strong><p>Local emergency numbers, health guidance, and the TIME TO FLY support line are always available inside every guide.</p></div><Link to="/support">Open travel support <ArrowRight /></Link></div></section></main>
}
