import { ArrowRight, BedDouble, Check, Map, MapPin, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'

export default function HotelDetails({ hotel, room, setRoom }) {
  const rooms = [
    { name: 'Caldera King Room', bed: '1 king bed', guests: 2, size: '32 m²', price: 420, image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1000&q=85' },
    { name: 'Sea View Suite', bed: '1 king bed', guests: 3, size: '48 m²', price: 680, image: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1000&q=85' },
    { name: 'Private Horizon Villa', bed: '1 king + sofa bed', guests: 4, size: '76 m²', price: 1040, image: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1000&q=85' },
  ]
  return <div className="hotel-detail-main"><div className="hotel-highlights"><span><MapPin /><p><strong>Exceptional location</strong><small>{hotel.distance} · nearby landmarks</small></p></span><span><BedDouble /><p><strong>Exceptional rooms</strong><small>Space, comfort, and thoughtful details</small></p></span><span><ShieldCheck /><p><strong>Flexible booking</strong><small>Clear options and real support</small></p></span></div><div className="hotel-copy"><span className="eyebrow"><i />The stay</span><h2>A quiet place with<br />a sense of place.</h2><p>{hotel.description}</p><p>From the first welcome to the final sunrise, every detail is designed to help the outside world feel a little farther away.</p><button className="text-link">Read the full story <ArrowRight size={15} /></button></div><div className="amenities-block"><h2>Amenities & services</h2><div>{['Pool', 'Breakfast', 'Wi-Fi', 'Gym', 'Parking', 'Spa', 'Restaurant', 'Airport shuttle'].map((item) => <span key={item}><Check />{item}</span>)}</div></div><div className="room-section"><div className="section-mini-head"><div><span className="eyebrow"><i />Choose your space</span><h2>Rooms & suites</h2></div><span>7 nights · 2 guests</span></div>{rooms.map((item) => <article className={room.name === item.name ? 'is-selected' : ''} key={item.name}><img src={item.image} alt={item.name} /><div><span>{item.size}</span><h3>{item.name}</h3><p><BedDouble />{item.bed} · Sleeps {item.guests}</p><span><Check />Breakfast included</span><span><ShieldCheck />Free cancellation until Oct 9</span></div><div><p><small>7 nights</small><strong>${(item.price * 7).toLocaleString()}</strong><span>${item.price} per night + taxes</span></p><button className="btn btn--dark" onClick={() => setRoom(item)}>{room.name === item.name ? 'Selected' : 'Select room'}</button></div></article>)}</div><div className="location-block"><div className="section-mini-head"><div><span className="eyebrow"><i />Around the neighborhood</span><h2>Close to what matters</h2></div><button className="btn btn--outline"><Map size={16} />Open in maps</button></div><div className="location-map"><div className="map-grid" /><span className="map-pin"><i /><b>{hotel.name}</b></span><div className="nearby-places"><p><strong>Old Town</strong><span>0.6 km · 7 min walk</span></p><p><strong>Waterfront</strong><span>1.8 km · 22 min walk</span></p></div></div></div></div>
}
