import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, FileText, Mail, MessageSquare, Paperclip, Phone, Send, ShieldCheck } from 'lucide-react'
import PageHero from './PageChrome'
import { useTravel } from '../context/TravelContext'

const supportTopics = [['Bookings & tickets', 'Changes, cancellations, and booking references'], ['Payments', 'Cards, refunds, and payment protection'], ['Flights', 'Schedules, baggage, and check-in'], ['Hotels & packages', 'Reservations, inclusions, and special requests'], ['Travel documents', 'Tickets, visas, and secure storage'], ['Accessibility', 'Travel support and special assistance']]

export default function SupportPage() {
  const { notify } = useTravel()
  const [form, setForm] = useState({ subject: '', category: 'Booking help', priority: 'Normal', message: '' })
  const [ticket, setTicket] = useState(null)
  const submit = (event) => { event.preventDefault(); if (!form.subject || !form.message) return notify('Add a subject and message to continue', 'error'); const id = `SUP-${Math.random().toString(36).slice(2, 7).toUpperCase()}`; setTicket(id); notify('Support request created'); setForm({ subject: '', category: 'Booking help', priority: 'Normal', message: '' }) }
  return <main id="main-content"><PageHero compact eyebrow="Help & support" title={<>Real people,<br /><em>right when you need them.</em></>} text="Get a clear answer, make a change, or talk to a travel expert—before, during, or after your journey." image="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=2200&q=90" /><section className="support-channels container"><article><span><MessageSquare /></span><div><small>Fastest</small><h3>Live chat</h3><p>Average response under 2 minutes</p></div><button onClick={() => window.dispatchEvent(new CustomEvent('ttf-open-flymate'))}>Start chat <ArrowRight /></button></article><article><span><Phone /></span><div><small>24 hours</small><h3>Call us</h3><p>+1 (888) 555-FLY</p></div><button onClick={() => notify('Calling +1 (888) 555-FLY')}>Call now <ArrowRight /></button></article><article><span><Mail /></span><div><small>Within 24 hours</small><h3>Email</h3><p>care@timetofly.com</p></div><button onClick={() => notify('Email app opened')}>Write to us <ArrowRight /></button></article></section><SupportForm form={form} setForm={setForm} submit={submit} ticket={ticket} /></main>
}

function SupportForm({ form, setForm, submit, ticket }) {
  return <><section className="section container support-topics"><div className="section-heading"><div><span className="eyebrow"><i />Find it fast</span><h2>What can we help with?</h2></div></div><div>{supportTopics.map(([title, text]) => <button key={title} onClick={() => { setForm({ ...form, category: title }); document.getElementById('support-form')?.scrollIntoView({ behavior: 'smooth' }) }}><span><FileText /></span><div><strong>{title}</strong><p>{text}</p></div><ArrowRight /></button>)}</div></section><section className="section support-form-section" id="support-form"><div className="container support-form-layout"><div><span className="eyebrow"><i />Send us a note</span><h2>Tell us what’s going on.</h2><p>Share the details and a travel specialist will get back to you. Most requests receive a response within one business day.</p><div className="support-promise"><ShieldCheck /><div><strong>Your information is secure</strong><p>Support requests are encrypted and only visible to authorized agents.</p></div></div></div><form onSubmit={submit}><div className="form-row"><label>Subject<input value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} placeholder="A short description" /></label><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option>Booking help</option><option>Cancellation help</option><option>Payment help</option><option>Flights</option><option>Hotels</option></select><ChevronDown /></label></div><div className="form-row"><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option>Normal</option><option>Urgent</option><option>Traveling now</option></select></label><label>Booking reference<input placeholder="TTF-000000" /></label></div><label>Message<textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Tell us how we can help…" /></label><button type="button" className="file-upload"><Paperclip />Attach screenshots or receipts<input type="file" /></button><button className="btn btn--dark" type="submit">Send request <Send /></button>{ticket && <p className="ticket-created"><Check />Request {ticket} is now in the queue. We’ll be in touch shortly.</p>}</form></div></section></>
}
